tasks:
  path: gulp-tasks/
src:
  path: src/
dest:
  path: dist/
style:
  path:
    src: src/style/
    compiled: compiled/css
    dest: dist/css/
image:
  path:
    src: src/image/
    dest: dist/image/
script:
  path:
    src: src/js/
    compiled: compiled/js
    dest: dist/js/
entry:
  path: index.js
buildTask:
  - "image:compress"
  - "script:concat"
  - "styles:minify"