tasks:
  path: gulp-tasks/
src:
  path: src/
dest:
  path: dist/
style:
  path:
    src: src/style/
    dest: dist/css/
image:
  path:
    src: src/image/
    dest: dist/image/
script:
  path:
    src: src/js/
    dest: dist/js/
entry:
  path: /index.js