tasks:
  path:
    - gulp-tasks/
  build:
    - "image:compress"
    - "scripts:compile"
    - "styles:compile"
styles:
  path:
    src:
      sass: src/styles/
      css: src/raw/css
    compiled: compiled/css
    dest: dist/css/
  autoprefix:
    browser: last 2 version
    env: ie 10
  targetName: app.min.css
image:
  path:
    src: src/raw/images/
    dest: dist/image/
  sprity:
    src: src/raw/images/**/*.{png,jpg,gif}
    style: src/style/sprity.scss
    format: png
    orientation: binary-tree
    processor: sass
    engine: gm
    name: sprity
    prefix: sprity
    dest: src/images/sprity-scss
  svgsprityconfig:
    shape:
      id:
        separator: '-'
    mode:
      css:
        dest: .
        sprite: dist/image/svg-sprite.svg
        prefix: .
        render:
          scss:
            dest: src/images/sprity-scss/svg-sprity.scss
scripts:
  path:
    applicationSrc: .
    dest: dist/Javascript
  targetName: app.min.js
